//theme: jekyll-theme-modernist
useheader: false 
include: [/gallery/, /gallery/*, /_data/galleryjson.json]
exclude: [/coldstorage/OriginalImages/, /coldstorage/OriginalImages/*]

show_drafts: false

baseurl: "/"
repository: "ImageLearning/Octocat-Dataset"

plugins:
  - jekyll-seo-tag
UA-161446082-1: UA-161446082-1
