//theme: jekyll-theme-modernist
useheader: false 
include: [/gallery/, /gallery/*, /_data/galleryjson.json]
exclude: [/coldstorage/OriginalImages/, /coldstorage/OriginalImages/*]

url: octocat-dataset.imagelearning.community

show_drafts: false

baseurl: "/"
repository: "ImageLearning/Octocat-Dataset"

plugins:
  - jekyll-seo-tag
google_analytics: UA-161446082-1
